---
schemaVersion: "0.1"
description: "Install docker on an instance and tags it properly"
parameters:
  InstanceId:
    type: String
    description: "Instance ID of an instance to install Docker to"
  build:
    type: String
    description: "The build of Docker to Install"
    default: "get" # Gets the default version of Docker
mainSteps:
  - name: AssertRunning
    action: aws:assertAwsResourceProperty
    isCritical: true
    onFailure: abort
    nextStep: installPackages
    inputs:
      Service: ec2
      API:  DescribeInstances
      InstanceIds:
        - "{{ InstanceId }}"
      PropertySelector: "$.Reservation[0].Instances[0].State.Name"
      DesiredValues:
        - "running"
- name: installPackages
  action: aws:runCommand
  inputs:
    DocumentName: install-docker
    InstanceIds:
      - "{{InstanceId}}"
    Parameters:
      build:
        - "{{build}}"
- name: createTags
  action: aws:createTags
  maxAttempts: 2
  timeoutSeconds: 60
  onFailure: Abort
  inputs:
    ResourceType: EC2
    ResourceIds:
    - "{{ InstanceId }}"
    Tags:
    - Key: docker-installed
      Value: TRUE  